language: php

cache:
    directories:
        - .phpunit
        - $HOME/.composer/cache/files

branches:
    only:
        - master
        - /^\d+\.(\d+|x)$/

matrix:
    include:
        # lowest dependencies
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-lowest --prefer-stable" SYMFONY_DEPRECATIONS_HELPER="weak"
        # Newest dependencies
        - php: 7.3
          env: COMPOSER_FLAGS="--prefer-stable"
        # Symfony 4.4
        - php: 7.4
          env: SYMFONY_REQUIRE="4.4.*" COMPOSER_FLAGS="--prefer-stable"
        # Symfony 5.0
        - php: 7.4
          env: SYMFONY_REQUIRE="5.0.*" PHP_CS=yes COMPOSER_FLAGS="--prefer-stable"
        # Newest dependencies
        - php: 7.4
          env: COMPOSER_FLAGS="--prefer-stable"
        # development dependencies
        - php: 7.4
          env: DEPENDENCIES='dev'
        # development dependencies
        - php: 8.0
          env: COMPOSER_FLAGS="--prefer-stable"
    allow_failures:
        # development dependencies
        - php: nightly
          env: DEPENDENCIES='dev'

before_install:
    - echo "memory_limit=4G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer global require --no-progress --no-scripts --no-plugins symfony/flex dev-master
    - if [ "$DEPENDENCIES" != "" ]; then composer config minimum-stability $DEPENDENCIES; fi
    - if [ "$SYMFONY_LTS" != "" ]; then composer require --dev --no-update symfony/lts=$SYMFONY_LTS; fi

install:
    - composer update $COMPOSER_FLAGS --prefer-dist
    - ./phpunit install

script:
    - ./phpunit
    - if [ "$PHP_CS" == "yes" ]; then vendor/bin/php-cs-fixer fix --verbose --diff --dry-run; fi
